package com.yongtao.ebuy.manager.pojo;

import java.util.Date;

public class OrderShipping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_phone
     *
     * @mbggenerated
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_mobile
     *
     * @mbggenerated
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_state
     *
     * @mbggenerated
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_city
     *
     * @mbggenerated
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_district
     *
     * @mbggenerated
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_address
     *
     * @mbggenerated
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.receiver_zip
     *
     * @mbggenerated
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_shipping.updated
     *
     * @mbggenerated
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.order_id
     *
     * @return the value of order_shipping.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.order_id
     *
     * @param orderId the value for order_shipping.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_name
     *
     * @return the value of order_shipping.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_name
     *
     * @param receiverName the value for order_shipping.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_phone
     *
     * @return the value of order_shipping.receiver_phone
     *
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_phone
     *
     * @param receiverPhone the value for order_shipping.receiver_phone
     *
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_mobile
     *
     * @return the value of order_shipping.receiver_mobile
     *
     * @mbggenerated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_mobile
     *
     * @param receiverMobile the value for order_shipping.receiver_mobile
     *
     * @mbggenerated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_state
     *
     * @return the value of order_shipping.receiver_state
     *
     * @mbggenerated
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_state
     *
     * @param receiverState the value for order_shipping.receiver_state
     *
     * @mbggenerated
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_city
     *
     * @return the value of order_shipping.receiver_city
     *
     * @mbggenerated
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_city
     *
     * @param receiverCity the value for order_shipping.receiver_city
     *
     * @mbggenerated
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_district
     *
     * @return the value of order_shipping.receiver_district
     *
     * @mbggenerated
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_district
     *
     * @param receiverDistrict the value for order_shipping.receiver_district
     *
     * @mbggenerated
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_address
     *
     * @return the value of order_shipping.receiver_address
     *
     * @mbggenerated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_address
     *
     * @param receiverAddress the value for order_shipping.receiver_address
     *
     * @mbggenerated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.receiver_zip
     *
     * @return the value of order_shipping.receiver_zip
     *
     * @mbggenerated
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.receiver_zip
     *
     * @param receiverZip the value for order_shipping.receiver_zip
     *
     * @mbggenerated
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.created
     *
     * @return the value of order_shipping.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.created
     *
     * @param created the value for order_shipping.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_shipping.updated
     *
     * @return the value of order_shipping.updated
     *
     * @mbggenerated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_shipping.updated
     *
     * @param updated the value for order_shipping.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}