package com.yongtao.ebuy.manager.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yongtao.ebuy.manager.pojo.ItemDesc;
import com.yongtao.ebuy.manager.pojo.ItemDescExample;

public interface ItemDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int countByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int deleteByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int insert(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int insertSelective(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    List<ItemDesc> selectByExampleWithBLOBs(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    List<ItemDesc> selectByExample(ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    ItemDesc selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ItemDesc record, @Param("example") ItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_desc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItemDesc record);
}